spring:
  datasource:
    hikari:      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/sample?useUnicode=true&amp;characterEncoding=UTF-8&amp;serverTimezone=UTC&amp;useSSL=false
      username: root
      password: "&YOUha6644"
      maximum-pool-size: 10
      connection-test-query: SELECT 1
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp
     
server:  servlet:    encoding:      charset: UTF-8
      enabled: true
      force: true